name: iOS

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    
    - uses: actions/checkout@v4.1.1
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    
    - name: Install MAUI workload
      run: dotnet workload install maui
    
    - name: Build
      run: dotnet build src/QuickApp/QuickApp.csproj -c Release -f:net8.0-ios

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        path: ./*
